name: cloudant_serverless_client
version: 4.0.4
description: A PouchDB alike for Dart. Uses lawndart for local storage and Wilt for CouchDB access.
homepage: https://github.com/astamiviswakarma/cloudant-serverless-client

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  wilt:
    git: https://github.com/astamiviswakarma/wilt.git
  json_object_lite: '^2.1.0'

dev_dependencies:
  test: '^1.9.4'
  build_runner: '^1.7.2'
  build_test: '^0.10.10'
  build_web_compilers: '^2.7.1'
